- name: Install SAP on AWS VM
  hosts: sap
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install SAP dependencies
      apt:
        name: ['libaio1', 'libaio-dev', 'unzip', 'wget']
        state: present

    - name: Download SAP installation script
      get_url:
        url: "https://sap.example.com/install.sh"
        dest: "/tmp/install.sh"
        mode: '0755'

    - name: Run SAP installation script
      command: sh /tmp/install.sh
